[package]
name = "rsql"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
color-eyre = "0.6.4"
crossterm = "0.29.0"
mysql = "26.0.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
ropey = "1.6.1"
